/**
==========================================================
AURA Trade OS
Command Type
Version : 0.0.7 Alpha
==========================================================
*/

export enum CommandType {
    SYSTEM_START = "SYSTEM_START",
    SYSTEM_STOP = "SYSTEM_STOP",
    SYSTEM_PAUSE = "SYSTEM_PAUSE",
    SYSTEM_RESUME = "SYSTEM_RESUME",
    SYSTEM_RESET = "SYSTEM_RESET",

    MARKET_REFRESH = "MARKET_REFRESH",
    MARKET_SUBSCRIBE = "MARKET_SUBSCRIBE",
    MARKET_UNSUBSCRIBE = "MARKET_UNSUBSCRIBE",

    STRATEGY_START = "STRATEGY_START",
    STRATEGY_STOP = "STRATEGY_STOP",
    STRATEGY_PAUSE = "STRATEGY_PAUSE",
    STRATEGY_RESUME = "STRATEGY_RESUME",

    RISK_CHECK = "RISK_CHECK",
    RISK_RESET = "RISK_RESET",

    ORDER_CREATE = "ORDER_CREATE",
    ORDER_CANCEL = "ORDER_CANCEL",
    ORDER_RETRY = "ORDER_RETRY",

    POSITION_OPEN = "POSITION_OPEN",
    POSITION_CLOSE = "POSITION_CLOSE",

    PORTFOLIO_REFRESH = "PORTFOLIO_REFRESH",

    TELEMETRY_FLUSH = "TELEMETRY_FLUSH",
}
